### ISSUE TITLE
Tracking issue for "untagged" models

### ISSUE THREAD

**Issue by cfi2017** [loadout-report/loadout.report#6]
Tracking issue for models not belonging to an endpoint group
1. Model Implementation
   - [x] BungieMembershipType
   - [ ] BungieCredentialType
   - [ ] SearchResultOfContentItemPublicContract
   - [ ] SearchResultOfPostResponse
   - [ ] BungieMembershipType[]
   - [ ] Interpolation.InterpolationPoint
   - [ ] Dates.DateRange
   - [ ] Interpolation.InterpolationPointFloat
   - [x] Links.HyperlinkReference
   - [ ] Tags.Models.Contracts.TagResponse
   - [ ] SearchResultOfGroupV2Card
   - [ ] SearchResultOfGroupMember
   - [ ] SearchResultOfGroupBan
   - [ ] SearchResultOfGroupMemberApplication
   - [ ] Entities.EntityActionResult
   - [ ] Exceptions.PlatformErrorCodes
   - [ ] SearchResultOfGroupMembership
   - [ ] SearchResultOfGroupPotentialMembership
   - [ ] Streaming.DropStateEnum
   - [ ] Components.ComponentResponse
   - [ ] Components.ComponentPrivacySetting
   - [ ] SingleComponentResponseOfDestinyVendorReceiptsComponent
   - [ ] SingleComponentResponseOfDestinyInventoryComponent
   - [ ] SingleComponentResponseOfDestinyProfileComponent
   - [ ] SingleComponentResponseOfDestinyPlatformSilverComponent
   - [ ] SingleComponentResponseOfDestinyKiosksComponent
   - [ ] SingleComponentResponseOfDestinyPlugSetsComponent
   - [ ] SingleComponentResponseOfDestinyProfileProgressionComponent
   - [ ] SingleComponentResponseOfDestinyPresentationNodesComponent
   - [ ] SingleComponentResponseOfDestinyProfileRecordsComponent
   - [ ] SingleComponentResponseOfDestinyProfileCollectiblesComponent
   - [ ] SingleComponentResponseOfDestinyProfileTransitoryComponent
   - [ ] SingleComponentResponseOfDestinyMetricsComponent
   - [ ] SingleComponentResponseOfDestinyStringVariablesComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCharacterComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyInventoryComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCharacterProgressionComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCharacterRenderComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCharacterActivitiesComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyKiosksComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyPlugSetsComponent
   - [ ] DestinyBaseItemComponentSetOfuint32
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemObjectivesComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemPerksComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyPresentationNodesComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCharacterRecordsComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCollectiblesComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyStringVariablesComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCraftablesComponent
   - [ ] DestinyBaseItemComponentSetOfint64
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemObjectivesComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemPerksComponent
   - [ ] DestinyItemComponentSetOfint64
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemInstanceComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemRenderComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemStatsComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemSocketsComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemReusablePlugsComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemPlugObjectivesComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemTalentGridComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCurrenciesComponent
   - [ ] SingleComponentResponseOfDestinyCharacterComponent
   - [ ] SingleComponentResponseOfDestinyCharacterProgressionComponent
   - [ ] SingleComponentResponseOfDestinyCharacterRenderComponent
   - [ ] SingleComponentResponseOfDestinyCharacterActivitiesComponent
   - [ ] SingleComponentResponseOfDestinyCharacterRecordsComponent
   - [ ] SingleComponentResponseOfDestinyCollectiblesComponent
   - [ ] SingleComponentResponseOfDestinyCurrenciesComponent
   - [ ] SingleComponentResponseOfDestinyItemComponent
   - [ ] SingleComponentResponseOfDestinyItemInstanceComponent
   - [ ] SingleComponentResponseOfDestinyItemObjectivesComponent
   - [ ] SingleComponentResponseOfDestinyItemPerksComponent
   - [ ] SingleComponentResponseOfDestinyItemRenderComponent
   - [ ] SingleComponentResponseOfDestinyItemStatsComponent
   - [ ] SingleComponentResponseOfDestinyItemTalentGridComponent
   - [ ] SingleComponentResponseOfDestinyItemSocketsComponent
   - [ ] SingleComponentResponseOfDestinyItemReusablePlugsComponent
   - [ ] SingleComponentResponseOfDestinyItemPlugObjectivesComponent
   - [ ] SingleComponentResponseOfDestinyVendorGroupComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyVendorComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyVendorCategoriesComponent
   - [ ] DestinyVendorSaleItemSetComponentOfDestinyVendorSaleItemComponent
   - [ ] DictionaryComponentResponseOfuint32AndPersonalDestinyVendorSaleItemSetComponent
   - [ ] DestinyBaseItemComponentSetOfint32
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemObjectivesComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemPerksComponent
   - [ ] DestinyItemComponentSetOfint32
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemInstanceComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemRenderComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemStatsComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemSocketsComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemReusablePlugsComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemPlugObjectivesComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemTalentGridComponent
   - [ ] SingleComponentResponseOfDestinyVendorComponent
   - [ ] SingleComponentResponseOfDestinyVendorCategoriesComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyVendorSaleItemComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyPublicVendorComponent
   - [ ] DestinyVendorSaleItemSetComponentOfDestinyPublicVendorSaleItemComponent
   - [ ] DictionaryComponentResponseOfuint32AndPublicDestinyVendorSaleItemSetComponent
   - [ ] DestinyItemComponentSetOfuint32
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemInstanceComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemRenderComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemStatsComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemSocketsComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemReusablePlugsComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemPlugObjectivesComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemTalentGridComponent
   - [ ] SearchResultOfDestinyEntitySearchResultItem
   - [ ] SearchResultOfTrendingEntry
   - [ ] SearchResultOfFireteamSummary
   - [ ] SearchResultOfFireteamResponse
   - [ ] GlobalAlert
   - [ ] GlobalAlertLevel
   - [ ] GlobalAlertType
   - [ ] StreamInfo
3. Endpoint Implementation
   - [ ] GET: /GetAvailableLocales/
   - [ ] GET: /Settings/
   - [ ] GET: /UserSystemOverrides/
   - [ ] GET: /GlobalAlerts/
4. Model Sanity Pass (usability improvements)
   - [ ] BungieMembershipType
   - [ ] BungieCredentialType
   - [ ] SearchResultOfContentItemPublicContract
   - [ ] SearchResultOfPostResponse
   - [ ] BungieMembershipType[]
   - [ ] Interpolation.InterpolationPoint
   - [ ] Dates.DateRange
   - [ ] Interpolation.InterpolationPointFloat
   - [ ] Links.HyperlinkReference
   - [ ] Tags.Models.Contracts.TagResponse
   - [ ] SearchResultOfGroupV2Card
   - [ ] SearchResultOfGroupMember
   - [ ] SearchResultOfGroupBan
   - [ ] SearchResultOfGroupMemberApplication
   - [ ] Entities.EntityActionResult
   - [ ] Exceptions.PlatformErrorCodes
   - [ ] SearchResultOfGroupMembership
   - [ ] SearchResultOfGroupPotentialMembership
   - [ ] Streaming.DropStateEnum
   - [ ] Components.ComponentResponse
   - [ ] Components.ComponentPrivacySetting
   - [ ] SingleComponentResponseOfDestinyVendorReceiptsComponent
   - [ ] SingleComponentResponseOfDestinyInventoryComponent
   - [ ] SingleComponentResponseOfDestinyProfileComponent
   - [ ] SingleComponentResponseOfDestinyPlatformSilverComponent
   - [ ] SingleComponentResponseOfDestinyKiosksComponent
   - [ ] SingleComponentResponseOfDestinyPlugSetsComponent
   - [ ] SingleComponentResponseOfDestinyProfileProgressionComponent
   - [ ] SingleComponentResponseOfDestinyPresentationNodesComponent
   - [ ] SingleComponentResponseOfDestinyProfileRecordsComponent
   - [ ] SingleComponentResponseOfDestinyProfileCollectiblesComponent
   - [ ] SingleComponentResponseOfDestinyProfileTransitoryComponent
   - [ ] SingleComponentResponseOfDestinyMetricsComponent
   - [ ] SingleComponentResponseOfDestinyStringVariablesComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCharacterComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyInventoryComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCharacterProgressionComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCharacterRenderComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCharacterActivitiesComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyKiosksComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyPlugSetsComponent
   - [ ] DestinyBaseItemComponentSetOfuint32
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemObjectivesComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemPerksComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyPresentationNodesComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCharacterRecordsComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCollectiblesComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyStringVariablesComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCraftablesComponent
   - [ ] DestinyBaseItemComponentSetOfint64
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemObjectivesComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemPerksComponent
   - [ ] DestinyItemComponentSetOfint64
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemInstanceComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemRenderComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemStatsComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemSocketsComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemReusablePlugsComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemPlugObjectivesComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemTalentGridComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCurrenciesComponent
   - [ ] SingleComponentResponseOfDestinyCharacterComponent
   - [ ] SingleComponentResponseOfDestinyCharacterProgressionComponent
   - [ ] SingleComponentResponseOfDestinyCharacterRenderComponent
   - [ ] SingleComponentResponseOfDestinyCharacterActivitiesComponent
   - [ ] SingleComponentResponseOfDestinyCharacterRecordsComponent
   - [ ] SingleComponentResponseOfDestinyCollectiblesComponent
   - [ ] SingleComponentResponseOfDestinyCurrenciesComponent
   - [ ] SingleComponentResponseOfDestinyItemComponent
   - [ ] SingleComponentResponseOfDestinyItemInstanceComponent
   - [ ] SingleComponentResponseOfDestinyItemObjectivesComponent
   - [ ] SingleComponentResponseOfDestinyItemPerksComponent
   - [ ] SingleComponentResponseOfDestinyItemRenderComponent
   - [ ] SingleComponentResponseOfDestinyItemStatsComponent
   - [ ] SingleComponentResponseOfDestinyItemTalentGridComponent
   - [ ] SingleComponentResponseOfDestinyItemSocketsComponent
   - [ ] SingleComponentResponseOfDestinyItemReusablePlugsComponent
   - [ ] SingleComponentResponseOfDestinyItemPlugObjectivesComponent
   - [ ] SingleComponentResponseOfDestinyVendorGroupComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyVendorComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyVendorCategoriesComponent
   - [ ] DestinyVendorSaleItemSetComponentOfDestinyVendorSaleItemComponent
   - [ ] DictionaryComponentResponseOfuint32AndPersonalDestinyVendorSaleItemSetComponent
   - [ ] DestinyBaseItemComponentSetOfint32
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemObjectivesComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemPerksComponent
   - [ ] DestinyItemComponentSetOfint32
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemInstanceComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemRenderComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemStatsComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemSocketsComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemReusablePlugsComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemPlugObjectivesComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemTalentGridComponent
   - [ ] SingleComponentResponseOfDestinyVendorComponent
   - [ ] SingleComponentResponseOfDestinyVendorCategoriesComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyVendorSaleItemComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyPublicVendorComponent
   - [ ] DestinyVendorSaleItemSetComponentOfDestinyPublicVendorSaleItemComponent
   - [ ] DictionaryComponentResponseOfuint32AndPublicDestinyVendorSaleItemSetComponent
   - [ ] DestinyItemComponentSetOfuint32
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemInstanceComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemRenderComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemStatsComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemSocketsComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemReusablePlugsComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemPlugObjectivesComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemTalentGridComponent
   - [ ] SearchResultOfDestinyEntitySearchResultItem
   - [ ] SearchResultOfTrendingEntry
   - [ ] SearchResultOfFireteamSummary
   - [ ] SearchResultOfFireteamResponse
   - [ ] GlobalAlert
   - [ ] GlobalAlertLevel
   - [ ] GlobalAlertType
   - [ ] StreamInfo
5. Live-data tests
   - [ ] BungieMembershipType
   - [ ] BungieCredentialType
   - [ ] SearchResultOfContentItemPublicContract
   - [ ] SearchResultOfPostResponse
   - [ ] BungieMembershipType[]
   - [ ] Interpolation.InterpolationPoint
   - [ ] Dates.DateRange
   - [ ] Interpolation.InterpolationPointFloat
   - [ ] Links.HyperlinkReference
   - [ ] Tags.Models.Contracts.TagResponse
   - [ ] SearchResultOfGroupV2Card
   - [ ] SearchResultOfGroupMember
   - [ ] SearchResultOfGroupBan
   - [ ] SearchResultOfGroupMemberApplication
   - [ ] Entities.EntityActionResult
   - [ ] Exceptions.PlatformErrorCodes
   - [ ] SearchResultOfGroupMembership
   - [ ] SearchResultOfGroupPotentialMembership
   - [ ] Streaming.DropStateEnum
   - [ ] Components.ComponentResponse
   - [ ] Components.ComponentPrivacySetting
   - [ ] SingleComponentResponseOfDestinyVendorReceiptsComponent
   - [ ] SingleComponentResponseOfDestinyInventoryComponent
   - [ ] SingleComponentResponseOfDestinyProfileComponent
   - [ ] SingleComponentResponseOfDestinyPlatformSilverComponent
   - [ ] SingleComponentResponseOfDestinyKiosksComponent
   - [ ] SingleComponentResponseOfDestinyPlugSetsComponent
   - [ ] SingleComponentResponseOfDestinyProfileProgressionComponent
   - [ ] SingleComponentResponseOfDestinyPresentationNodesComponent
   - [ ] SingleComponentResponseOfDestinyProfileRecordsComponent
   - [ ] SingleComponentResponseOfDestinyProfileCollectiblesComponent
   - [ ] SingleComponentResponseOfDestinyProfileTransitoryComponent
   - [ ] SingleComponentResponseOfDestinyMetricsComponent
   - [ ] SingleComponentResponseOfDestinyStringVariablesComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCharacterComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyInventoryComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCharacterProgressionComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCharacterRenderComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCharacterActivitiesComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyKiosksComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyPlugSetsComponent
   - [ ] DestinyBaseItemComponentSetOfuint32
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemObjectivesComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemPerksComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyPresentationNodesComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCharacterRecordsComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCollectiblesComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyStringVariablesComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCraftablesComponent
   - [ ] DestinyBaseItemComponentSetOfint64
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemObjectivesComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemPerksComponent
   - [ ] DestinyItemComponentSetOfint64
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemInstanceComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemRenderComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemStatsComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemSocketsComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemReusablePlugsComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemPlugObjectivesComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyItemTalentGridComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent
   - [ ] DictionaryComponentResponseOfint64AndDestinyCurrenciesComponent
   - [ ] SingleComponentResponseOfDestinyCharacterComponent
   - [ ] SingleComponentResponseOfDestinyCharacterProgressionComponent
   - [ ] SingleComponentResponseOfDestinyCharacterRenderComponent
   - [ ] SingleComponentResponseOfDestinyCharacterActivitiesComponent
   - [ ] SingleComponentResponseOfDestinyCharacterRecordsComponent
   - [ ] SingleComponentResponseOfDestinyCollectiblesComponent
   - [ ] SingleComponentResponseOfDestinyCurrenciesComponent
   - [ ] SingleComponentResponseOfDestinyItemComponent
   - [ ] SingleComponentResponseOfDestinyItemInstanceComponent
   - [ ] SingleComponentResponseOfDestinyItemObjectivesComponent
   - [ ] SingleComponentResponseOfDestinyItemPerksComponent
   - [ ] SingleComponentResponseOfDestinyItemRenderComponent
   - [ ] SingleComponentResponseOfDestinyItemStatsComponent
   - [ ] SingleComponentResponseOfDestinyItemTalentGridComponent
   - [ ] SingleComponentResponseOfDestinyItemSocketsComponent
   - [ ] SingleComponentResponseOfDestinyItemReusablePlugsComponent
   - [ ] SingleComponentResponseOfDestinyItemPlugObjectivesComponent
   - [ ] SingleComponentResponseOfDestinyVendorGroupComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyVendorComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyVendorCategoriesComponent
   - [ ] DestinyVendorSaleItemSetComponentOfDestinyVendorSaleItemComponent
   - [ ] DictionaryComponentResponseOfuint32AndPersonalDestinyVendorSaleItemSetComponent
   - [ ] DestinyBaseItemComponentSetOfint32
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemObjectivesComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemPerksComponent
   - [ ] DestinyItemComponentSetOfint32
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemInstanceComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemRenderComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemStatsComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemSocketsComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemReusablePlugsComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemPlugObjectivesComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyItemTalentGridComponent
   - [ ] SingleComponentResponseOfDestinyVendorComponent
   - [ ] SingleComponentResponseOfDestinyVendorCategoriesComponent
   - [ ] DictionaryComponentResponseOfint32AndDestinyVendorSaleItemComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyPublicVendorComponent
   - [ ] DestinyVendorSaleItemSetComponentOfDestinyPublicVendorSaleItemComponent
   - [ ] DictionaryComponentResponseOfuint32AndPublicDestinyVendorSaleItemSetComponent
   - [ ] DestinyItemComponentSetOfuint32
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemInstanceComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemRenderComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemStatsComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemSocketsComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemReusablePlugsComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemPlugObjectivesComponent
   - [ ] DictionaryComponentResponseOfuint32AndDestinyItemTalentGridComponent
   - [ ] SearchResultOfDestinyEntitySearchResultItem
   - [ ] SearchResultOfTrendingEntry
   - [ ] SearchResultOfFireteamSummary
   - [ ] SearchResultOfFireteamResponse
   - [ ] GlobalAlert
   - [ ] GlobalAlertLevel
   - [ ] GlobalAlertType
   - [ ] StreamInfo
